### ISSUE TITLE
和模型對話聊天紀錄的相關api

### ISSUE THREAD

**Issue by LinZKai** [nccu-mis-g8/backend#10]
想要有一隻api是可以回傳使用者所創建人物的名字和其對話紀錄

**Comment by y1lichen** [comment]
@LinZKai 前端是否能記錄對話生成csv直接使用upload api回傳呢？

**Comment by LinZKai** [comment]
> @LinZKai 前端是否能記錄對話生成csv直接使用upload api回傳呢？

應該可以做到! csv裡面的格式有要求嗎
