### ISSUE TITLE
前端 - 新增使用者icon可更換大頭貼

### ISSUE THREAD

**Issue by ndl1n** [nccu-mis-g8/backend#14]
1. 參考網頁版FB，在個人頁面點選大頭貼照後，可查看大頭貼照或選擇大頭貼照
2. 可直接Copy FB source code
3. 在使用者上傳大頭貼照後，打上傳照片的api

**Comment by LinZKai** [comment]
基本上已完成，只剩下串接後端上傳照片API
![螢幕擷取畫面 2024-09-28 020106](https://github.com/user-attachments/assets/1c49230b-c97c-4a4b-bc9d-09c28f0f1e4d)
![螢幕擷取畫面 2024-09-28 020046](https://github.com/user-attachments/assets/8af6260c-4cc9-49d4-be4b-a9eebef183ee)

**Comment by ndl1n** [comment]
收到，已有api可以串了
