### ISSUE TITLE
photo 相關

### ISSUE THREAD

**Issue by ndl1n** [nccu-mis-g8/backend#50]
1. 只要跟該user有關的，全部存在同一個資料夾，用user_id來區分
2. 個人頭像儲存照片(upload_photo)跟模型頭像儲存照片(trained_model)的形式**(你懂的)**[可以看4]
3. 要寫一支get model photo的api(聊天室頁面可以用)
4. get user photo 拿照片的形式也一樣
5. 資料庫一樣存檔名，回傳給前端用拼接的改成傳網址
6. 防火牆怎麼設才可以直接連

**Comment by JERRYzx7** [comment]
4、5、6 暫時完成
