### ISSUE TITLE
目前缺的或需要更新的api

### ISSUE THREAD

**Issue by LinZKai** [nccu-mis-g8/backend#57]
11/10
1. 拿取使用者的頭像 (尚未併入)
2. 使用連結進行分享模型api (尚未併入)
3. 缺少獲取某使用者所擁有的所有模型的api，並且內容還需要加上他們的分享模型連結
4. 聊天的api是否需要指定是和哪個模型聊天 (給模型id之類的)，並且需要給前五筆的聊天訊息 (目前還沒有輸入這個參數的地方)
5. 是否需要存取聊天紀錄，如果要的話就需要新增獲取和某模型聊天紀錄的api (或是在3.的部分也加上模型各自的聊天紀錄)
6. 使用者自行創建模型的api，上次使用有問題，可能是資料庫和code之間尚未整合
7. 記事本事件的部分，目前創建事件的部分新增了一些欄位需要更新 (如圖)，可能連帶其他事件相關api都需要更新
8. 缺少獲取**所有**事件的api，以及利用**年份**去找事件的api
10.  訓練以及查看訓練進度的api，因為目前無法串接，所以不確定有沒有問題，訓練進度的部分目前有三種狀態(未上傳任何資料、訓練中、訓練完成)，需要確定後端回傳的參數是否能完整表現出目前是哪種狀態

![image](https://github.com/user-attachments/assets/c67928b0-86af-4ec4-b58c-caec3ca7f82c)

**Comment by ndl1n** [comment]
1搞定 7.8分給祐辰

**Comment by ndl1n** [comment]
2檢查過了，到時候等chat改好再實際走一次流程

**Comment by ndl1n** [comment]
6也搞定了

**Comment by ndl1n** [comment]
3好了
